# Generated by Django 6.0 on 2025-12-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_options_alter_hotel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='api_key',
            field=models.CharField(default='5cd041db49f4f2418e4aa9f9a89fb99b006cbb7025205e21f27fae3157fc7dff', max_length=64, unique=True, verbose_name='API ключ'),
        ),
    ]
