# Generated by Django 6.0 on 2025-12-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='api_key',
            field=models.CharField(default='581cc9b5af9dacf9e28fda6a4a796cd6db09b6d80ab885f295b428c508108bc3', max_length=64, unique=True, verbose_name='API ключ'),
        ),
    ]
